import type {Metadata} from "next";
import {Anonymous_Pro} from "next/font/google";
import "./globals.css";
import TelegramInit from "@/components/TelegramInit";

const anonymous_Pro = Anonymous_Pro({
    variable: "--font-geist-sans",
    weight: ['700', '400'],
    subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
        <body
            className={`${anonymous_Pro.variable} antialiased`}
        >
        <TelegramInit>
            {children}
        </TelegramInit>
        </body>
        </html>
    );
}
